using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Vaxometer.ApplicationSettings;
using Vaxometer.BackgroundService;
using Vaxometer.Manager;
using Vaxometer.Middlewares;
using Vaxometer.MongoOperations.IocExtensions;
using Vaxometer.Repository;

namespace Vaxometer
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
            services.AddHttpContextAccessor();
            services.AddHttpClient();
            services.AddOptions();
            services.AddMemoryCache();
            services.AddAutoMapper(AppDomain.CurrentDomain.GetAssemblies());
            services.AddMongoOperations(Configuration);
            services.AddMongoOperations(Configuration);
            services.Configure<ApplicationUrls>(Configuration.GetSection(nameof(ApplicationUrls)));
            services.AddSingleton<IApplicationUrls>(x => x.GetRequiredService<IOptions<ApplicationUrls>>().Value);
            services.AddScoped<IVexoManager, VexoManager>();
            services.AddScoped<IVaccineManager, VaccineManager>();
            services.AddScoped<ICowinRepository, CowinRepository>();
            services.AddScoped<IDataRepository, DataRepository>();
            services.AddHostedService<BackgroundDataRefershTask>();

            services.AddSwaggerGen(options =>
            {
                options.SwaggerDoc("v1", new Microsoft.OpenApi.Models.OpenApiInfo
                {
                    Title = "Vaxometer API helps you determine centers by VaccineType, AgeGroup, Date,PinCode",
                    Version = "v1",
                    //Description = "Displays data of 7 days. Also help find available slot in 2 months",
                });
                //Locate the XML file being generated by ASP.NET...
                var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.XML";
                var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
                options.IncludeXmlComments(xmlPath);
            });

        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();
            app.UseRouting();
            app.UseGlobalExceptionHandlerMiddleware();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });

            app.UseSwagger();
            app.UseSwaggerUI(options => options.SwaggerEndpoint("/swagger/v1/swagger.json", "Vaxometer: Powered by Cowin Open API"));

        }
    }
}
